name: medicamina_ui
description: Open source precision medicine UI.
version: 1.0.0+1
repository: https://github.com/medicamina/ui
issue_tracker: https://github.com/medicamina/ui/issues
documentation: https://docs.medicamina.us/
funding: [https://patreon.com/medicamina_github]

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  community_material_icon: ^5.9.55
  url_strategy: ^0.2.0
  syncfusion_flutter_maps: ^21.1.39
  event: ^2.1.2
  badges: ^3.1.1
  google_fonts: ^4.0.3
  flutter_modular: ^5.0.3
  date_time_picker:
    git:
      url: https://github.com/arsarsars1/date_time_picker.git
      ref: new_version
  fl_chart: ^0.62.0
  flutter_svg: ^2.0.5
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.10
  graphview: ^1.2.0
  firebase_core: ^2.24.2
  universal_io: ^2.2.2
  intl: 
  calendar_timeline: ^1.1.2
  device_preview: ^1.1.0
  random_date: ^0.0.7
  calendar_view: ^1.0.4
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/world_map.json
    - assets/images/