name: medicamina_ui
description: Open source precision medicine UI.
version: 1.0.0+1
repository: https://github.com/medicamina/ui
issue_tracker: https://github.com/medicamina/ui/issues
documentation: https://docs.medicamina.us/
funding: [https://patreon.com/medicamina_github]

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  community_material_icon: ^5.9.55
  url_strategy: ^0.2.0
  syncfusion_flutter_maps: ^21.1.39
  event: ^2.1.2
  badges: ^3.1.1
  supabase_flutter: ^1.2.2
  google_fonts: ^4.0.3
  flutter_modular: ^5.0.3
  date_time_picker: ^2.1.0
  fl_chart: ^0.62.0
  flutter_svg: ^2.0.5
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.10
  graphview: ^1.2.0
  firebase_core: ^2.24.2
  universal_io: ^2.2.2
  intl: 
  calendar_timeline: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/world_map.json
    - assets/images/