name: medicamina
description: Open source precision medicine.
version: 1.0.0+1
repository: https://github.com/medicamina/medicamina
issue_tracker: https://github.com/medicamina/medicamina/issues

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  community_material_icon: ^5.9.55
  url_strategy: ^0.2.0
  syncfusion_flutter_maps: ^20.1.59
  event: ^2.1.2
  badges: ^2.0.3
  supabase_flutter: ^1.2.2
  google_fonts: ^3.0.1
  flutter_modular: ^5.0.3
  date_time_picker: ^2.1.0
  fl_chart: ^0.55.2
  flutter_svg: ^1.1.6
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - world_map.json
    - assets/images/